### ISSUE TITLE
Add an option for hiding placeholder elements

### ISSUE THREAD

**Issue by wenlzhang** [mlhetland/skeldoc.sty#4]
When drafting a paper, one may send the manuscript to collaborators for reviewing. For this, it would be great if one can hide all/specific placeholder elements by using an option when loading the package.

It might be even more helpful if one can choose to hide certain types of placeholder elements, e.g. those created with `\skelnote{}`.

**Comment by mlhetland** [comment]
I just started looking a little bit at this. Not sure what the progress will be, but for now I've added an option (`hide-numbers`) to hide the numbers in the margin (which would hide `\skelnote`s, for example, as long as you also avoid `\printskelnotes`). You can find it in the branch [mlh/hiding](https://github.com/mlhetland/skeldoc.sty/tree/mlh/hiding).

I'm thinking about other hiding, but I'm not sure what would be the way to go. Hiding placeholders would in general change the "shape" of your document, and I'm not sure it seems super useful to me. And if you *do* wish to hide things, the most likely scenario seems perhaps to just hide everything? (I don't quite see when you'd want, for example, to hide all placeholder bullet lists in your document, but nothing else …)

At the moment I'm sort of leaning toward only having this option to hide the numbers (which would address your specific `\skelnote` request), but perhaps you have some input?

**Comment by mlhetland** [comment]
Looking through my notes, I see that I *do* have a to-do about hiding all blocks, where the motivation was to get a more stripped-down outline-like document (i.e., if you have only headlines + `\skel`-elements). But I'm not sure if it's really useful.

**Comment by wenlzhang** [comment]
Thanks for the update!

Regarding hiding `\skelnote` and other placeholder elements, my use cases would be as follows:

- For `\skelnote` elements, I may want to hide both the numbers on the margin and the notes at the end of the manuscript at the same time.
- For placeholder elements like `\skelpar`, I may have two use cases:
    - Sometimes, I may want to hide the numbers on the margin and the notes at the end but keep the corresponding placeholders in the main document. This is mainly because I may want to show that there should be something there, but I do not want to show my personal notes regarding them.
    - Sometimes, I may want to hide everything, i.e. the numbers, notes and placeholders. This is the same as your use case, i.e. yielding a "more stripped-down outline-like document".

**Comment by mlhetland** [comment]
> For `\skelnote` elements, I may want to hide both the numbers on the margin and the notes at the end of the manuscript at the same time.

Right. My thought was that one could hide the numbers and comment out `\printskelnotes`, but I guess there's really no case in which you'd want to only hide the numbers, and still print the notes. I guess I could change `hide-numbers` to `hide-notes`, which would hide the numbers *and* make `\printskelnotes` a no-op.

> Sometimes, I may want to hide the numbers on the margin and the notes at the end but keep the corresponding placeholders in the main document. This is mainly because I may want to show that there should be something there, but I do not want to show my personal notes regarding them.

Right. That's what would happen with the `hide-notes` option.

> Sometimes, I may want to hide everything, i.e. the numbers, notes and placeholders. This is the same as your use case, i.e. yielding a "more stripped-down outline-like document".

Right. Is this mostly a hypothetical scenario, or something you've had use for?

My thinking is that as soon as you start working on your document, entering some text here and there, hiding the placeholders would quickly produce a rather weird result; i.e., that this would primarily be useful *before* any such incremental work. (But that could still be useful, of course – e.g., having a document with only headlines and placeholders w/notes.)

**Comment by wenlzhang** [comment]
> I guess I could change `hide-numbers` to `hide-notes`

This would be great!

> Is this mostly a hypothetical scenario, or something you've had use for?

To be honest, I haven't used this scenario before, and this is a potential use case for me.

> hiding the placeholders would quickly produce a rather weird result; i.e., that this would primarily be useful _before_ any such incremental work. (But that could still be useful, of course – e.g., having a document with only headlines and placeholders w/notes.)

I agree with these two points. Therefore, if this is not too difficult or time-consuming to implement, it could still be valuable in the for certain use cases. :-)

**Comment by mlhetland** [comment]
> > I guess I could change `hide-numbers` to `hide-notes`
> 
> This would be great!

Heh, I just realized this is an automatic consequence of my current implementation, because it suppresses all `\endnotemark`s (and therefore, no endnotes exist). But I might as well suppress the actual `\endnotetext` part, too.

> > Is this mostly a hypothetical scenario, or something you've had use for?
> 
> To be honest, I haven't used this scenario before, and this is a potential use case for me.
> 
> > hiding the placeholders would quickly produce a rather weird result; i.e., that this would primarily be useful _before_ any such incremental work. (But that could still be useful, of course – e.g., having a document with only headlines and placeholders w/notes.)
> 
> I agree with these two points. Therefore, if this is not too difficult or time-consuming to implement, it could still be valuable for certain use cases. :-)

Right. No, it shouldn't be hard to do :-) Just looking at how I can avoid cluttering things too much.

**Comment by mlhetland** [comment]
I've updated the branch with a tentative implementation of `hide-notes` and `hide-all`. It would be great if you could test them out, and see if they match your expectations :-)

(Should just be a matter of downloading [`skeldoc.sty` from that branch](https://github.com/mlhetland/skeldoc.sty/blob/mlh/hiding/skeldoc.sty) into the same directory as your document, for example.)

**Comment by wenlzhang** [comment]
> I've updated the branch with a tentative implementation of `hide-notes` and `hide-all`. It would be great if you could test them out, and see if they match your expectations :-)

Great! I will test them in the next days when writing my paper. 😃

**Comment by mlhetland** [comment]
Does this seem to work on your end?

**Comment by mlhetland** [comment]
> Apologies for the delayed response. I was thinking to confirm this together with a few related feature requests, but haven't summarized them yet. 😅

No problem!-D

> In the past two months, I have been using these options when writing my papers, and they work like a charm.

Excellent! I'll probably just merge it, then.

**Comment by mlhetland** [comment]
Fixed by #5.
